trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: Templates/vars.yml

jobs:
  - job:
    variables:
      VMNAME: 'USS-SRV-11'
    steps:
    - template: Templates/vm-creation-steps.yml