trigger:
- master

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: JaspersAzureSubscription
  resourceGroupName: 'exampleRG'
  location: 'eastus'
  templateFile: '$(system.defaultworkingdirectory)/AzureResourceFiles/vm.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  displayName: Deploy Azure Resources
  env:
    adminPassword: adminPassword=$(adminPassword)
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters adminUsername='administrator' adminPassword=$(adminPassword)